M48
; DRILL file KiCad 10.0.5-1-g226df246f3 date 2026-09-22T12:47:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-22T12:47:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5-1-g226df246f3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X117.5Y-3.5
X117.5Y-61.5
X166.5Y-3.5
X166.5Y-61.5
T2
X5.0Y-5.0
X5.0Y-115.0
X110.0Y-5.0
X165.0Y-115.0
M30
