// GENERATED by make_params.py from the KiCad exports - do not edit by hand.
// All dimensions in mm.  See make_params.py for the derivation.
CLR = 0.5;
WALL = 3.0;
FLOOR = 3.0;
LID_T = 3.0;
LID_LIP_H = 4.0;
LID_LIP_T = 2.0;
LID_LIP_CLR = 0.25;
T_PCB = 1.6;
BOSS_H = 6.0;
BOSS_D = 8.0;
INSERT_D = 4.0;
INSERT_DEPTH = 7.0;
STANDOFF = 18.0;
CORNER_R = 3.0;
TIER_PITCH = 19.6;
BOARD = 100.0;
INNER = 101.0;
OUTER = 107.0;
Z_LID_UNDER = 87.4;
Z_OUTER_TOP = 90.4;
HOLES = [[9.5, 97.5], [9.5, 9.5], [97.5, 97.5], [97.5, 9.5]];
TIER_Z_TOP = [10.6, 30.2, 49.8, 69.4];
// windows: [y0, y1, z0, z1]  on the +X wall
WINDOWS_PX = [[19.295, 31.295, 30.5, 41.5], [19.295, 31.295, 50.1, 61.1]];
// holes: [x, z, d]  on the -Y wall
HOLES_MY = [[75.64, 35.2, 5.0], [75.64, 54.8, 5.0]];
// notches: [x0, x1, z0, z1]  on the -Y wall, open to the top edge
NOTCHES_MY = [[40.45, 64.77, 72.4, 87.4]];
