'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={power:'Power',digital:'Digital',left:'Left channel',right:'Right channel'}, stages=['Prepare','Sort components','Sockets & access','Resistors & diodes','Small capacitors','Connectors & bulk caps','Wire links','Inspect & insert ICs','First power & finish','Testing · start with visual guide'];
const key='vinyl-adc-assembly-v1';let state={checks:{},notes:{},modes:{power:'single',digital:'single'},board:'power',stage:0},data,selected='',zoom=1,pan=[0,0];
try{const x=JSON.parse(localStorage.getItem(key));if(x&&x.checks&&x.notes&&x.modes)state={...state,...x}}catch{}
let storageOK=true;function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch{storageOK=false;toast('Browser storage unavailable. Save a backup to retain progress.')}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4500)}
const source=b=>b==='left'||b==='right'?'channel_l':b,board=()=>data.boards[source(state.board)],isChannel=()=>['left','right'].includes(state.board),double=()=>isChannel()||state.modes[state.board]==='double';
const id=s=>state.board+':'+s,checked=s=>!!state.checks[id(s)],check=(s,text)=>`<label class="check"><input type="checkbox" data-check="${esc(s)}" ${checked(s)?'checked':''}><span>${text}</span></label>`;
function normalParts(){return board().parts.filter(p=>!['mount','wire'].includes(p.kind))}
function topPins(p){return p.pads.filter(a=>a.top)}
function filtered(parts){const q=$('#search').value.toLowerCase();return parts.filter(p=>(!$('#toponly').checked||topPins(p).length)&&(!$('#unfinished').checked||!checked('solder:'+p.ref))&&JSON.stringify([p.ref,p.value,p.pads.map(a=>a.net)]).toLowerCase().includes(q))}
function partRows(parts){const rows=filtered(parts);return `<div class="card parts">${rows.map(p=>`<div class="part ${selected===p.ref?'selected':''} ${checked('solder:'+p.ref)?'done':''}" data-part="${p.ref}" tabindex="0" role="button"><span class="ref">${p.ref}</span><span class="value">${esc(p.value)}<small style="display:block">${p.kind==='socket'?'Fit socket now · IC later':p.kind}</small></span>${topPins(p).length?`<span class="badge">${double()?'TOP':'LINK'} · ${topPins(p).map(a=>a.pin).join(', ')}</span>`:''}<span>${checked('solder:'+p.ref)?'✓':'→'}</span></div>`).join('')||'<p style="padding:16px">No components match these filters.</p>'}</div>`}
const card=(title,body)=>`<article class="card"><h2>${title}</h2>${body}</article>`;
function render(){if(!names[state.board])state.board='power';if(!stages[state.stage])state.stage=0;
 $('#boards').innerHTML=Object.entries(names).map(([b,n])=>`<button data-board="${b}" class="${state.board===b?'active':''}">${n}<small>${b==='left'?'J21 shunt 1–2':b==='right'?'J21 shunt 2–3':b==='power'?'Supply & reference':'Clock & Pi interface'}</small></button>`).join('');
 $('#stages').innerHTML=stages.map((s,i)=>`<button data-stage="${i}" class="${state.stage===i?'active':''}"><small>${String(i+1).padStart(2,'0')}</small>${s}</button>`).join('');
 const count=normalParts().filter(p=>checked('solder:'+p.ref)).length,total=normalParts().length;
 $('#overall').textContent=`${Object.keys(names).reduce((n,b)=>n+data.boards[source(b)].parts.filter(p=>!['mount','wire'].includes(p.kind)&&state.checks[b+':solder:'+p.ref]).length,0)} / 109 component positions soldered`;
 $('#intro').innerHTML=`<p class="eyebrow">${names[state.board].toUpperCase()} / STEP ${String(state.stage+1).padStart(2,'0')}</p><h1>${stages[state.stage]}</h1><p class="subtitle">${isChannel()?'Same KiCad artwork, separate progress for each channel.':'Work on one board at a time.'} ${count} of ${total} positions soldered.</p><progress value="${count}" max="${total}"></progress>`;
 let html='';const b=board();
 if(state.stage===0){html=card('Before placing anything',`<p>Match the bare board to the map and the KiCad file below. The map starts looking down onto the component side: X increases right, Y increases down. Flip the view only when turning the board over.</p>${check('prep:match','I matched the mounting holes, bus header and pad pattern to this PCB revision.')}${check('prep:clean','Copper is clean; drilled holes are open; isolation channels have no copper burrs or shorts.')}${check('prep:label',`I labelled this physical board <strong>${names[state.board]}</strong> on a non-copper edge.`)}<p><strong>Do not populate the whole board before soldering.</strong> Fit and solder a small group at a time. Socket pins and top-side pads need access before tall parts go in.</p>`);
 html+=card('How this board was made',isChannel()?'<p>Double-sided, unplated holes. A lead does not connect the two copper faces until you solder each required face. There are <strong>20 top joints, including 6 socket pins</strong>, on each channel.</p>':`<p>The fabrication notes specify bottom copper and insulated wire links for this board. Choose the construction of your actual board:</p><select id="mode"><option value="single" ${!double()?'selected':''}>Bottom copper + wire links</option><option value="double" ${double()?'selected':''}>Both copper sides milled</option></select><p>Changing this choice changes the joint and link instructions.</p>`);
 html+=card('Bench setup',check('prep:tools','Ready: multimeter, fine-tip soldering iron, flux, solder, cutters, insulated hookup wire, magnifier and board holder.')+check('prep:access','I checked that my sockets and headers allow access to every marked component-side pad before seating them.')+'<p>Keep ICs out of sockets until soldering and continuity checks are complete. Do not trim leads needed for a top joint until both faces are finished.</p>');
 }else if(state.stage===1){const groups={};for(const p of normalParts()){const k=p.value+'|'+p.footprint;(groups[k]??=[]).push(p)}html=card('Pull parts from the bin','<p>Quantities below are for this physical board only. Measure resistors before installation; similar E96 values are easy to confuse. Socket sizes come from the actual footprints.</p>');
 for(const [k,ps]of Object.entries(groups)){if(!filtered(ps).length)continue;html+=card(`${ps.length} × ${esc(ps[0].value)}`,`<p>${ps.map(p=>`<button data-part="${p.ref}">${p.ref}</button>`).join(' ')}<br><small>${esc(ps[0].footprint)}</small></p>${ps[0].kind==='resistor'?resistorGraphic(ps[0].value):''}${check('sort:'+k,ps[0].kind==='socket'?`Collected ${ps.length} IC${ps.length>1?'s':''} and ${ps.length} matching ${ps[0].pads.length}-pin socket${ps.length>1?'s':''}.`:'Value and package checked; parts set aside.')}`)}
 html+=card('Additional build items','<p>Insulated wire for the links; one shunt for each channel J21 and the digital clock selector J1; stacking bus connectors suited to each tier; mounting hardware. These are not extra schematic component positions.</p>');
 }else if(state.stage>=2&&state.stage<=5){const kinds={2:['socket'],3:['resistor','diode'],4:['capacitor'],5:['connector','electrolytic']}[state.stage];html=card('Fit → solder → inspect',state.stage===2?`<p>Install empty sockets, one at a time. Align pin 1 with the numbered pad on the map and in KiCad. Tack two opposite pins, check seating, then complete joints.</p><div class="warning">${double()?'Solder the amber component-side socket pins now. Check tip access before pushing the socket flush; do not hide an unsoldered pad beneath its body.':'Install required wire connections to socket pins before surrounding parts obstruct them. On digital: U8.3 → WL2A (BCLK), U8.11 → WL3A (DIN). Open Wire links now to locate the anchors, then return here.'}</div>`:state.stage===3?'<p>Measure each resistor, fit to the displayed pad pair, and solder this group before proceeding. Diode band goes to pad 1 (cathode). Keep leads from touching unrelated bare copper.</p>':state.stage===4?'<p>Check each value: 100n, 1n5 and 220p are not interchangeable. 2u2 is the film input capacitor. Confirm actual lead pitch before fitting.</p>':'<p>Fit tall parts only after nearby socket and passive top joints are finished. The bus connector type depends on stack position. RV20 uses a 3-pin header footprint for a wired potentiometer, not a Bourns trimmer footprint.</p>');html+=partRows(normalParts().filter(p=>kinds.includes(p.kind)));}
 else if(state.stage===6){if(double()){html=card('Top copper joint audit','<p>These routes are copper on your board. Solder every highlighted lead to the component-side pad as well as completing underside soldering. No vias are present in the current files.</p>')+partRows(b.parts.filter(p=>topPins(p).length));}else{html=card('Install insulated wire links','<p>F.Cu lines represent electrical connections that bottom-only copper cannot make. Install the WL pairs below. The digital board also needs two socket-to-link connections. Route insulated wire clear of sockets, mounting holes and the bus; solder to leads/pads and check continuity at the named endpoints.</p>');let links=[];const wires=b.parts.filter(p=>p.kind==='wire');for(const p of wires.filter(p=>p.ref.endsWith('A'))){const mate=wires.find(x=>x.ref===p.ref.slice(0,-1)+'B');if(mate)links.push([p.pads[0],mate.pads[0]])}for(const p of normalParts())for(const pad of topPins(p)){const candidates=wires.flatMap(w=>w.pads).filter(a=>a.net===pad.net).sort((a,c)=>Math.hypot(a.at[0]-pad.at[0],a.at[1]-pad.at[1])-Math.hypot(c.at[0]-pad.at[0],c.at[1]-pad.at[1]));if(candidates.length)links.push([pad,candidates[0]])}
 for(const [a,c]of links)html+=card(`${a.ref}.${a.pin} ↔ ${c.ref}.${c.pin}`,`<p><code>${esc(a.net)}</code><br><small>${a.at.join(', ')} → ${c.at.join(', ')} mm</small></p><button data-part="${a.ref}">Locate ${a.ref}</button> <button data-part="${c.ref}">Locate ${c.ref}</button>${check('wire:'+a.ref+'.'+a.pin+':'+c.ref+'.'+c.pin,'Wire installed; continuity measured between these endpoints.')}`);
 } }
 else if(state.stage===7){html=card('Unpowered inspection',check('inspect:bottom','Every populated lead is wetted to its underside pad; no bridges, loose wires or clipped lead fragments.')+check('inspect:top',double()?'Every listed top-side joint is soldered and inspected, especially beneath sockets and headers.':'Every listed wire link, including socket connections, is installed and continuity tested.')+check('inspect:rails','With power disconnected, I checked supply rails against GND and each other for sustained near-zero resistance (allow capacitors to charge).')+check('inspect:polarity','Electrolytic polarity, diode bands, socket pin 1, and connector numbering all match KiCad.'));
 html+=card('Current KiCad DRC',`<p>${b.drc.unconnected.length} unconnected items. ${b.drc.violations.length} reported violations. This checks PCB connectivity; it assumes plated through-holes and does not verify hand soldering or a milled board.</p>${b.drc.violations.filter(v=>v.type!=='silk_overlap').map(v=>`<div class="warning">${esc(v.description)}<br>${v.items.map(i=>esc(i.description)+' at '+i.pos.x+', '+i.pos.y+' mm').join('<br>')}</div>`).join('')||'<p>Remaining reports are silkscreen clearance overlaps.</p>'}${state.board==='digital'?check('inspect:c11','I inspected the BCLK path beside C11 pads 1 and 2. For wire construction, insulation keeps the wire clear; for top copper, I measured that BCLK is not shorted to +5V or GND.'):''}<a href="generated/${source(state.board)}-drc.json">Read complete DRC report</a>`);
 html+=card('Insert ICs after inspection','<p>Disconnect power. Check the IC marking against the socket reference, straighten pins, and align its pin 1 with the map. Never use text orientation as the pin-1 reference.</p>'+normalParts().filter(p=>p.kind==='socket').map(p=>check('ic:'+p.ref,`${p.ref}: <strong>${esc(p.value)}</strong> inserted in its ${p.pads.length}-pin socket; orientation checked.`)).join(''));
 }else if(state.stage===9){html=renderBench();}else{html=finish();}
 $('#content').innerHTML=html;$('#source').innerHTML=`Source: <code>${esc(b.source)}</code><br>SHA-256: ${b.sha256}<br>Extracted ${esc(data.generated)} · Physical milling revision must match this snapshot. Re-run <code>python assembly/generate.py</code> after PCB edits, then reload. Progress is not proof of electrical function.`;
 if(!selected||!b.parts.find(p=>p.ref===selected))selected=normalParts()[0].ref;draw();detail();save();}
function finish(){let h=card('Test this board', '<p>For your current BNC probes and missing oscillator, use the visual wiring guide above with WaveForms manually.</p><a class="button" href="#visual-wiring">Open visual wiring guide ↑</a>');h+=card('Set the selectors',isChannel()?`<p>Fit J21 <strong>${state.board==='left'?'1–2 for LEFT':'2–3 for RIGHT'}</strong>. Both boards use left-channel reference names in KiCad; do not add 40 to the reference numbers. Label the physical boards.</p>${check('finish:selector','Correct channel shunt installed and checked against pad numbers.')}`:state.board==='digital'?`<p>J1 pin 1 is the local oscillator path; pin 2 is the selected clock path; pin 3 is GPCLK0. With X1 missing, use <strong>J1 2–3 for the external W1 clock</strong> as shown in the visual guide. J1 1–2 is only for the installed local oscillator. Do not fit both shunts.</p>${check('finish:external-selector','External clock selector set to 2–3 for the current missing-X1 build.')}`:'<p>The pump relies on PUMP from the digital board. Do not expect a valid negative rail with the power board alone and no pump clock.</p>');
 h+=card('Check the stacking bus','<p>Power at the bottom, then right and left channels, digital at the top. Verify actual connector sex, pin engagement and clearance before tightening hardware. Check pin 1 end-to-end; a reversed supply bus can short rails.</p>'+pinTable(board().parts.find(p=>p.value==='2x8 BUS'))+check('finish:bus','Bus pin numbering verified across all four boards, with power disconnected.'));
 h+=card('First powered checks','<p>Use a current-limited regulated supply and keep the Raspberry Pi disconnected for initial checks. The repository does not specify a validated current limit or acceptance tolerances; establish these before applying power. Never insert or remove ICs or stack connectors while powered.</p><p>The digital divider provides the pump clock needed for the negative supply, so bring up the power and digital functions together before adding channel loads. Provide +3V3 for the digital interface as its schematic requires; avoid back-feeding any unpowered supply.</p><p>Measure relative to GND: bus pin 2 targets +5 V; pin 16 is the negative supply; pins 4 and 6 target +2.5 V and −2.5 V references. Check the actual values against the schematic before connecting channels. Turn off immediately if current limiting persists or a part heats unexpectedly.</p>'+check('finish:rails','Measured and recorded supplies/reference voltages; confirmed suitable before adding channels.')+'<p>With an oscilloscope, check the design clock targets: oscillator/CLK6M 6.144 MHz, MCLK 1.536 MHz, BCLK 3.072 MHz, modulator clock 1.536 MHz, LRCLK 48 kHz. Check logic levels at the Pi interface before connecting it.</p>'+check('finish:clock','Clock frequencies and interface levels measured and recorded.'));
 if(state.board==='digital')h+=card('Pi interface header is custom','<p>J2 is an 8-pin custom interface, not a direct 40-pin Pi header. Its PCB pinout is below. Match signal names to the Pi wiring documentation; verify +3V3 and +5V separately.</p>'+pinTable(board().parts.find(p=>p.ref==='J2')));
 h+=card('Complete the hardware build',check('finish:channels','Both channels connected one at a time with power off; supplies rechecked under load.')+check('finish:signal','Signal and clock activity verified before connecting the Pi; analog input comes from a phono preamplifier.')+check('finish:mechanical','Stack secure, no copper contacting hardware, wiring strain relieved, and enclosure clearances checked.')+'<p>These steps finish assembly and initial electrical checks. Audio capture software, gain calibration and measured audio performance require a separate validation session; no successful audio test is implied by the checkboxes.</p>');return h;}
function pinTable(p){return p?`<div class="table-scroll"><table><thead><tr><th>Pin</th><th>Net</th><th>X, Y mm</th></tr></thead><tbody>${p.pads.map(a=>`<tr><td>${a.pin}</td><td>${esc(a.net||'Unconnected')}</td><td>${a.at.join(', ')}</td></tr>`).join('')}</tbody></table></div>`:''}
function detail(){const p=board().parts.find(p=>p.ref===selected);if(!p)return;let tip=p.kind==='electrolytic'?'Positive lead → pad 1; negative stripe → pad 2. Follow the nets below: C5 and C6 have their positive lead at GND, not at the negative rail.':p.kind==='diode'?'Cathode band → pad 1. Anode → pad 2.':p.kind==='socket'?`Install a ${p.pads.length}-pin socket now; insert ${p.value} only after inspection. The square pad marks pin 1. ${p.ref==='X1'?'The oscillator can has fewer pins than the socket; check its own pin numbering.':''}`:p.ref==='RV20'?'This is a 3-pin header for the gain potentiometer. Wire the pot wiper to pad 2; verify the real pot terminal numbering.':p.kind==='resistor'?'Measure before fitting. No polarity. Follow the actual pad spacing; keep the body and bent lead clear of other bare copper.':p.kind==='capacitor'?'Non-polarized capacitor. Check its value and lead pitch.':p.kind==='wire'?'Wire-link anchor, not a purchased component. Use the Wire links step to find its partner.':'Match pin numbering and physical connector orientation in KiCad.';
 $('#detail').innerHTML=`<p class="eyebrow">SELECTED COMPONENT</p><h2>${p.ref} <span class="muted">/ ${esc(p.value)}</span></h2><p><small>${esc(p.footprint)}<br>Anchor X ${p.at[0]}, Y ${p.at[1]} mm · ${p.angle}° in KiCad</small></p><p>${esc(tip)}</p>${p.kind==='resistor'?resistorGraphic(p.value):''}${topPins(p).length?`<div class="warning"><strong>${double()?'Solder on BOTH sides':'Wire connection required'}:</strong> pin${topPins(p).length>1?'s':''} ${topPins(p).map(a=>a.pin).join(', ')}. ${double()?'Complete these before nearby parts block access.':'The top-layer connection is absent from bottom-only copper. See Wire links.'}</div>`:''}${pinTable(p)}${!['mount','wire'].includes(p.kind)?check('place:'+p.ref,p.kind==='socket'?'Socket placed; pin 1 checked.':'Part placed; value and orientation checked.')+check('solder:'+p.ref,'Underside soldered and inspected.')+topPins(p).filter(()=>double()).map(a=>check('top:'+p.ref+'.'+a.pin,`Top joint ${p.ref}.${a.pin} soldered and continuity checked.`)).join(''):''}<label class="muted">Bench notes for ${p.ref}<textarea class="note-input" id="note" placeholder="Measurements, substitutions, things to revisit…">${esc(state.notes[id(p.ref)]||'')}</textarea></label>`;}
function draw(){const b=board(),bottom=$('#view').value==='bottom',[x,y,w,h]=b.bounds,cx=x+w/2,cy=y+h/2;const tx=a=>bottom?2*cx-a:a;const vb=[cx-w/(2*zoom)+pan[0]-3,cy-h/(2*zoom)+pan[1]-3,w/zoom+6,h/zoom+6];
 let s=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb.join(' ')}" role="img" aria-label="${names[state.board]} PCB ${bottom?'mirrored underside':'component side'}"><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="1" fill="#15251d" stroke="#50745d" stroke-width=".4"/>`;
 if($('#traces').checked)s+=b.tracks.map(t=>`<line x1="${tx(t.a[0])}" y1="${t.a[1]}" x2="${tx(t.b[0])}" y2="${t.b[1]}" stroke="${t.layer==='top'?'#966c43':'#315b54'}" stroke-width=".35" opacity=".65"/>`).join('');
 for(const p of b.parts){const active=p.ref===selected;const xs=p.pads.map(a=>tx(a.at[0])),ys=p.pads.map(a=>a.at[1]);if(!xs.length)continue;
 s+=`<g class="fp" data-part="${p.ref}"><title>${p.ref} · ${esc(p.value)}</title><rect x="${Math.min(...xs)-1.3}" y="${Math.min(...ys)-1.3}" width="${Math.max(...xs)-Math.min(...xs)+2.6}" height="${Math.max(...ys)-Math.min(...ys)+2.6}" rx=".5" fill="${active?'#4e713b':'transparent'}" fill-opacity=".4" stroke="${active?'#bef58b':'#3d5146'}" stroke-width="${active?'.5':'.15'}"/>`;
 for(const a of p.pads){const c=active?'#bef58b':a.top?'#ffc477':'#809a89';s+=a.pin==='1'?`<rect x="${tx(a.at[0])-0.75}" y="${a.at[1]-0.75}" width="1.5" height="1.5" fill="${c}"/>`:`<circle cx="${tx(a.at[0])}" cy="${a.at[1]}" r="${p.kind==='mount'?1.6:.7}" fill="${c}"/>`;s+=`<circle cx="${tx(a.at[0])}" cy="${a.at[1]}" r=".25" fill="#0e1913"/>`;if(active)s+=`<text x="${tx(a.at[0])+1}" y="${a.at[1]-.7}" font-size="1.55">${a.pin}</text>`}
 s+=`<text x="${Math.min(...xs)}" y="${Math.min(...ys)-1.9}" font-size="${active?2.1:1.6}" font-weight="${active?700:400}">${p.ref}</text></g>`;
 }s+='</svg>';$('#map').innerHTML=s;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-board]'),s=e.target.closest('[data-stage]'),p=e.target.closest('[data-part]');if(b){state.board=b.dataset.board;selected='';zoom=1;pan=[0,0];render()}else if(s){state.stage=+s.dataset.stage;render()}else if(p){selected=p.dataset.part;draw();detail();document.querySelectorAll('.part').forEach(el=>el.classList.toggle('selected',el.dataset.part===selected))}});
document.addEventListener('keydown',e=>{if(e.target.matches('.part')&&['Enter',' '].includes(e.key)){e.preventDefault();e.target.click()}});
document.addEventListener('change',e=>{if(e.target.dataset.check){state.checks[id(e.target.dataset.check)]=e.target.checked;save();render()}if(e.target.id==='mode'){state.modes[state.board]=e.target.value;render()}});
$('#detail').addEventListener('input',e=>{if(e.target.id==='note'){state.notes[id(selected)]=e.target.value;save()}});
for(const sel of ['#search','#unfinished','#toponly'])$(sel).addEventListener('input',()=>render());for(const sel of ['#view','#traces'])$(sel).addEventListener('change',draw);
$('#zoomin').onclick=()=>{zoom=Math.min(5,zoom*1.4);draw()};$('#zoomout').onclick=()=>{zoom=Math.max(1,zoom/1.4);draw()};$('#fit').onclick=()=>{zoom=1;pan=[0,0];draw()};
let drag;$('#map').addEventListener('pointerdown',e=>{if(e.target.closest('[data-part]'))return;drag=[e.clientX,e.clientY,...pan];$('#map').setPointerCapture(e.pointerId)});$('#map').addEventListener('pointermove',e=>{if(!drag)return;const scale=Math.max(board().bounds[2],board().bounds[3])/$('#map').clientWidth/zoom;pan=[drag[2]-(e.clientX-drag[0])*scale,drag[3]-(e.clientY-drag[1])*scale];draw()});$('#map').addEventListener('pointerup',()=>drag=null);
$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({format:'vinyl-adc-assembly-v1',state},null,2)],{type:'application/json'}));a.download='vinyl-adc-assembly-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#import').onchange=async e=>{try{const v=JSON.parse(await e.target.files[0].text());if(v.format!=='vinyl-adc-assembly-v1'||!v.state||!v.state.checks||!v.state.notes||!v.state.modes)throw Error();if(!confirm('Replace this browser’s progress with the saved backup?'))return;state=v.state;render();toast('Progress restored')}catch{toast('Could not restore: choose an assembly progress backup.')}e.target.value=''};
Promise.all(['generated/boards.json','bench/plans.json'].map(url=>fetch(url).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}))).then(([d,p])=>{data=d;benchPlans=p;render();refreshBenchHistory()}).catch(e=>{$('#intro').innerHTML='<h1>Could not load PCB data</h1><p>Start the local server with python assembly/serve.py, then open http://localhost:8080.</p>';console.error(e)});
