let benchPlans,benchHistory=[],benchReportCache={};
function renderBench(){
 const plan=benchPlans.boards[state.board];const useAD3=state.bench3v3!==false;
 const command=`python assembly/bench/run.py ${state.board}${state.board!=='power'&&useAD3?' --ad3-3v3':''}`;
 let h=card('Test this board before moving on',`<p>${esc(benchPlans.order)}</p><p>Use your <strong>Analog Discovery 3 + bench DC supply</strong>. The scripts guide each probe change and stop on failed measurements. Keep the Pi disconnected.</p><p><a href="bench/README.md">Full test instructions</a> · <a href="downloads/README.md">WaveForms & Adept installers</a></p>`);
 h+=card('Install the SDK once',`<p>WaveForms 3.25.1 and Adept Runtime are installed. The WaveForms menu launcher includes the Adept library directory. The command below is only needed if reinstalling.</p><pre class="command"><code>sudo pacman -U /home/mads/Projects/vinyl-adc/assembly/downloads/arch-build/digilent.waveforms-3.25.1-1-x86_64.pkg.tar.zst</code></pre>${check('bench:sdk','WaveForms installed; devices command lists my AD3.')}<p><small>Then close WaveForms before using the scripts. No AD3 was connected during software verification.</small></p>`);
 h+=card('Run the guided test',`${state.board!=='power'?`<label class="check"><input id="bench3v3" type="checkbox" ${useAD3?'checked':''}><span>Use AD3 <strong>V+ at 3.3 V</strong> for digital J2.3. Uncheck only if a separate regulated bench output supplies 3.3 V.</span></label>`:''}<p>From the project directory, run:</p><pre class="command test-command"><code>${command}</code></pre><button data-copy-command="${command}">Copy command</button> <button id="bench-refresh">Refresh results</button><p><small>The terminal asks you to turn power off before rewiring and confirms the connections before enabling an AD3 output. The bench supply remains under your manual control.</small></p><details><summary>Check the SDK or rehearse without hardware</summary><p><code>python assembly/bench/run.py devices</code><br><code>python assembly/bench/run.py ${state.board} --plan</code><br><code>python assembly/bench/run.py ${state.board} --simulate</code></p><p>Simulation exercises the test software. It never counts as a measured board pass.</p></details>`);
 h+=card('Measured results',benchResults());
 h+=card('Connect the bench',`<ol>${benchPlans.common.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${check('bench:unpowered','Assembly inspection complete; no sustained rail-to-ground shorts; polarity and all top joints / wire links verified.')}`);
 for(const step of plan.steps){h+=card(step.title,`<p>${esc(step.instructions)}</p>${step.connections.length?`<div class="table-scroll"><table><thead><tr><th>AD3 / connection</th><th>PCB point</th><th>Net / KiCad X,Y</th></tr></thead><tbody>${step.connections.map(c=>{
 const part=board().parts.find(p=>p.ref===c.ref),pad=part?.pads.find(p=>p.pin===c.pin);
 return `<tr><td>${esc(c.lead)}</td><td><button data-part="${c.ref}">${c.ref}.${c.pin}</button></td><td>${esc(c.net)}<br><small>${pad?pad.at.join(', ')+' mm':'See fixture instructions'}</small></td></tr>`}).join('')}</tbody></table></div>`:''}<p class="test-expect"><strong>Expected:</strong> ${esc(step.expect)}</p>`)}
 h+=card('What a pass establishes','<p>A PASS means this run met the listed functional screening limits. The analog voltage, ripple, density and gain limits are initial engineering checks, not a validated production specification. The tests do not certify SNR, THD, noise floor, calibrated input gain or 24-bit performance.</p><p>Power testing is unloaded first; recheck rails with both channels installed before closing the enclosure. Current readings, resistor substitutions and RV20 settings belong in your bench notes.</p><p>Sources: '+benchPlans.sources.filter(s=>s.url.startsWith('https')).map(s=>`<a href="${s.url}" target="_blank" rel="noreferrer">${esc(s.title)}</a>`).join(' · ')+'</p>');
 return card('Use the visual wiring guide for your current equipment', '<p>Your BNC adapter, 10× probes and missing oscillator are covered by the graphical guide at the top of this page. Start there and use WaveForms manually.</p><p><a class="button" href="#visual-wiring">Open visual wiring guide ↑</a></p><p>The SDK procedures below are for the original 1× flywire fixture. Digital/channel scripts also require the installed oscillator. Do not run them with the current BNC fixture.</p>') + '<details><summary>Original SDK procedures and saved results — different fixture</summary>' + h + '</details>';
}
function benchResults(){
 const runs=benchHistory.filter(r=>r.board===state.board);
 if(!runs.length)return '<p class="muted">No test reports yet. Run the command, then refresh results. Assembly checkboxes do not count as a test pass.</p>';
 return runs.slice(0,12).map(r=>{const current=r.sources&&Object.entries(r.sources).every(([k,v])=>data.boards[k]?.sha256===v);const status=r.simulated?'SIMULATED':current?r.status:'STALE REVISION';const validID=/^[a-zA-Z0-9-]+$/.test(r.id);return `<div class="bench-result"><span class="result-status ${status==='PASS'?'passed':status==='FAIL'||status==='ERROR'?'failed':''}">${esc(status)}</span> <small>${esc(new Date(r.finished||r.started).toLocaleString())}</small>${r.simulated?`<p>Synthetic outcome: ${esc(r.simulation_outcome)}. No hardware was measured.</p>`:''}${!current?'<p>PCB hashes differ or are missing. This report cannot validate the current board revision.</p>':''}${r.error?`<p>${esc(r.error)}</p>`:''}${validID?`<a href="bench/results/${r.id}/report.json" target="_blank">Raw report JSON</a> <button data-bench-report="${r.id}">Show measurements</button>${benchReportCache[r.id]?benchReportDetails(benchReportCache[r.id]):''}`:''}</div>`}).join('');
}
async function refreshBenchHistory(){try{const response=await fetch('bench/results/index.json',{cache:'no-store'});benchHistory=response.ok?await response.json():[];if(!Array.isArray(benchHistory))benchHistory=[];if(state.stage===9)render()}catch{toast('Could not read reports; check the local server.')}}
document.addEventListener('click',async e=>{const copy=e.target.closest('[data-copy-command]');if(copy){try{await navigator.clipboard.writeText(copy.dataset.copyCommand);toast('Test command copied')}catch{toast('Select and copy the command above.')}}if(e.target.id==='bench-refresh')refreshBenchHistory();if(e.target.closest('[data-stage="9"]'))refreshBenchHistory()});
document.addEventListener('change',e=>{if(e.target.id==='bench3v3'){state.bench3v3=e.target.checked;save();render()}});

function benchReportDetails(r){return (r.steps||[]).map(s=>`<details><summary>${esc(s.id)} · ${esc(s.status)}</summary><div class="table-scroll"><table><thead><tr><th>Measurement</th><th>Observed</th><th>Allowed</th><th>Result</th></tr></thead><tbody>${(s.metrics||[]).map(m=>`<tr><td>${esc(m.name)}</td><td>${m.value===null?'Invalid':Number(m.value).toPrecision(5)} ${esc(m.unit||'')}</td><td>${esc(m.min??'—')} … ${esc(m.max??'—')}</td><td>${esc(m.status)}</td></tr>`).join('')}</tbody></table></div>${(s.captures||[]).filter(c=>/^[a-zA-Z0-9_.-]+$/.test(c.file)).map(c=>`<p><a href="bench/results/${r.id}/${c.file}" download>${esc(c.file)}</a> · ${c.samples} samples at ${Number(c.sample_rate_hz).toPrecision(5)} Hz</p>`).join('')}</details>`).join('')}
document.addEventListener('click',async e=>{const button=e.target.closest('[data-bench-report]');if(!button)return;const rid=button.dataset.benchReport;if(!/^[a-zA-Z0-9-]+$/.test(rid))return;try{const response=await fetch(`bench/results/${rid}/report.json`);if(!response.ok)throw Error();const report=await response.json();if(report.format!=='vinyl-adc-bench-report-v1'||report.id!==rid||!Array.isArray(report.steps))throw Error();benchReportCache[rid]=report;render()}catch{toast('Could not load this measurement report.')}});
