M48
; DRILL file KiCad 10.0.6 date 2026-09-25T00:46:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T00:46:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X65.5Y-3.5
X65.5Y-61.5
X114.5Y-3.5
X114.5Y-61.5
T2
X3.5Y-3.5
X3.5Y-84.5
X114.5Y-84.5
M30
