M48
; DRILL file KiCad 10.0.6 date 2026-09-25T00:38:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T00:38:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X87.5Y-3.5
X87.5Y-61.5
X136.5Y-3.5
X136.5Y-61.5
T2
X3.5Y-3.5
X3.5Y-132.5
X136.5Y-132.5
M30
